import { ArrowLeft, ArrowRight } from "lucide-react";
import Link from "next/link";

import type { Locale } from "@/i18n/config";
import { getProjectPath, getProjectsPath } from "@/i18n/routing";
import type { LocaleContent } from "@/i18n/types";
import { joinClassNames } from "@/lib/utils";
import type { Project } from "@/types/project";

export function ProjectNavigation({ content, locale, nextProject, previousProject }: { content: LocaleContent; locale: Locale; nextProject?: Project; previousProject?: Project }) {
  const copy = content.ui.project.navigation;
  return <nav aria-label={copy.returnToProjects} className="border-t border-border py-12 sm:py-14"><Link className="inline-flex min-h-11 items-center rounded-sm font-mono text-xs text-foreground-muted transition-colors hover:text-primary-light focus-visible:outline-offset-2" href={getProjectsPath(locale)}>{copy.returnToProjects}</Link><div className="mt-6 grid gap-4 sm:grid-cols-2">{previousProject ? <Link aria-label={`${copy.previousProject}: ${previousProject.title}`} className="group flex min-h-28 items-center gap-4 rounded-xl border border-border bg-card p-5 transition-[border-color,background-color] duration-200 hover:border-primary/60 hover:bg-primary/5 focus-visible:outline-offset-2 motion-reduce:transition-none" href={getProjectPath(locale, previousProject.slug)}><ArrowLeft aria-hidden="true" className="shrink-0 text-primary-light transition-transform group-hover:-translate-x-0.5 motion-reduce:transform-none" size={18} strokeWidth={1.8} /><span><span className="font-mono text-[0.6875rem] text-foreground-muted">{copy.previous}</span><span className="mt-2 block font-medium text-foreground">{previousProject.title}</span></span></Link> : null}{nextProject ? <Link aria-label={`${copy.nextProject}: ${nextProject.title}`} className={joinClassNames("group flex min-h-28 items-center justify-between gap-4 rounded-xl border border-border bg-card p-5 text-right transition-[border-color,background-color] duration-200 hover:border-primary/60 hover:bg-primary/5 focus-visible:outline-offset-2 motion-reduce:transition-none", !previousProject && "sm:col-start-2")} href={getProjectPath(locale, nextProject.slug)}><span className="ml-auto"><span className="font-mono text-[0.6875rem] text-foreground-muted">{copy.next}</span><span className="mt-2 block font-medium text-foreground">{nextProject.title}</span></span><ArrowRight aria-hidden="true" className="shrink-0 text-primary-light transition-transform group-hover:translate-x-0.5 motion-reduce:transform-none" size={18} strokeWidth={1.8} /></Link> : null}</div></nav>;
}
